"""add categories table and todo category/tags

Revision ID: 1473b855e26a
Revises: d73001c3fa47
Create Date: 2026-08-25 14:36:31.247482

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1473b855e26a'
down_revision: str | Sequence[str] | None = 'd73001c3fa47'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # 创建 categories 表（模型 Category；此前缺失导致云端迁移链在下方外键处失败）
    op.create_table(
        "categories",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column(
            "user_id",
            sa.Uuid(),
            sa.ForeignKey("users.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("color", sa.String(length=16), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), server_default=sa.func.now(), nullable=False),
    )
    op.create_index(op.f("ix_categories_user_id"), "categories", ["user_id"], unique=False)
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("todos", sa.Column("category_id", sa.Uuid(), nullable=True))
    op.add_column("todos", sa.Column("tags", sa.JSON(), server_default="[]", nullable=False))
    op.create_index(op.f("ix_todos_category_id"), "todos", ["category_id"], unique=False)
    op.create_foreign_key(None, "todos", "categories", ["category_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "todos", type_="foreignkey")
    op.drop_index(op.f("ix_todos_category_id"), table_name="todos")
    op.drop_column("todos", "tags")
    op.drop_column("todos", "category_id")
    # ### end Alembic commands ###
    op.drop_index(op.f("ix_categories_user_id"), table_name="categories")
    op.drop_table("categories")
