"""add memory_facts table

Revision ID: 2898b892e706
Revises: 1473b855e26a
Create Date: 2026-08-25 15:10:39.539105

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '2898b892e706'
down_revision: str | Sequence[str] | None = '1473b855e26a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
